#---------------------------------#
#      general configuration      #
#---------------------------------#

version: "{build}"

branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

install:
  - cmd: git submodule -q update --init

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build:
  project: src/Toolbelt.sln
  publish_nuget: true
  verbosity: minimal

before_build:
  - cmd: nuget restore src/Toolbelt.sln
  - ps: .\tools\appveyor\scripts\update-build-version.ps1

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  - provider: Environment
    name: s3
    artifact: to-publish

  - provider: Environment
    name: chocolatey
    on:
      release_tag: true

before_deploy:
  - ps: .\tools\appveyor\scripts\declare-release-tag.ps1
  - ps: .\tools\custom-scripts\create-zip-file.ps1
