#---------------------------------#
#      general configuration      #
#---------------------------------#

version: "{build}"

branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

install:
  - cmd: git submodule -q update --init

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build:
  project: src/Toolbelt.sln
  publish_nuget: true
  verbosity: minimal

before_build:
  - cmd: nuget restore src/Toolbelt.sln
  - ps: .\tools\appveyor\scripts\update-build-version.ps1
